//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BASE_MATERIAL_NEW
    {
        public decimal RECORD_ID { get; set; }
        public string ERP_CODE { get; set; }
        public string ERP_NAME { get; set; }
        public string FAC_CODE { get; set; }
        public string FAC_NAME { get; set; }
        public string ISBF { get; set; }
        public string ISST { get; set; }
        public string ISUSE { get; set; }
        public string MAT_DESC { get; set; }
        public string MAT_TYPE { get; set; }
    }
}
