//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T_BKYL : DbContext
    {
        public T_BKYL()
            : base("name=T_BKYL")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_QUALITY_MIX_PHY_INSET> T_QUALITY_MIX_PHY_INSET { get; set; }
        public virtual DbSet<T_SINTER_MATERIAL_RATIO> T_SINTER_MATERIAL_RATIO { get; set; }
        public virtual DbSet<T_MATERIAL_METERING_MAP> T_MATERIAL_METERING_MAP { get; set; }
    }
}
