//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COST_TITLE_CONFIG
    {
        public Nullable<decimal> RECORD_ID { get; set; }
        public string MAT_TYPE { get; set; }
        public string COST_CENTER { get; set; }
        public string COST_CENTER_DESCR { get; set; }
        public string MAT_CODE { get; set; }
        public string MAT_CODE_DESC { get; set; }
        public string COST_TITLE { get; set; }
        public string COST_TITLE_DESC { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> C_H2O { get; set; }
    }
}
