//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ENERGY_TEAM_CONSUMPTION
    {
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string SHIFTS { get; set; }
        public string TAEM { get; set; }
        public Nullable<System.DateTime> WORK_BEGIN_TIME { get; set; }
        public Nullable<System.DateTime> WORK_END_TIME { get; set; }
        public string MATERIAL_CODE { get; set; }
        public string MATERIAL_NAME { get; set; }
        public Nullable<decimal> CONSUMPTION_SUM { get; set; }
        public Nullable<decimal> SPECIFIC_CONSUMPTION { get; set; }
        public decimal ID { get; set; }
        public string ID_PLCNAME { get; set; }
    }
}
