//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ENERGY_CONSUME
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> P3AI_405651F { get; set; }
        public Nullable<decimal> P3AI_405661F { get; set; }
        public Nullable<decimal> P3AI_405671F { get; set; }
        public Nullable<decimal> PLCNYAI_406006F { get; set; }
        public Nullable<decimal> PLCNYAI_406016F { get; set; }
        public Nullable<decimal> PLCNYAI_406026F { get; set; }
        public Nullable<decimal> PLCNYAI_406036F { get; set; }
        public Nullable<decimal> PLCNYAI_406046F { get; set; }
        public Nullable<decimal> PLCNYAI_406056F { get; set; }
        public Nullable<decimal> PLCNYAI_408206F { get; set; }
        public Nullable<decimal> PLCNYAI_408346F { get; set; }
        public Nullable<decimal> P1AI_408411F { get; set; }
        public Nullable<decimal> P2AI_408721F { get; set; }
        public Nullable<decimal> P3AI_405781F { get; set; }
        public Nullable<decimal> P3AI_405791F { get; set; }
        public Nullable<decimal> PLCNYAI_408306F { get; set; }
        public Nullable<decimal> PLCNYAI_408436F { get; set; }
        public Nullable<decimal> PLCNYAI_408336F { get; set; }
        public Nullable<decimal> PLCNYAI_408466F { get; set; }
    }
}
