//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INSERT_QUAL_SJK
    {
        public string MAT_SAMPLE_NO { get; set; }
        public Nullable<decimal> TFE { get; set; }
        public Nullable<decimal> SIO2 { get; set; }
        public Nullable<decimal> AL2O3 { get; set; }
        public Nullable<decimal> CAO { get; set; }
        public Nullable<decimal> MGO { get; set; }
        public Nullable<decimal> P { get; set; }
        public Nullable<decimal> S { get; set; }
        public Nullable<decimal> K2O { get; set; }
        public Nullable<decimal> NA2O { get; set; }
        public Nullable<decimal> MNO { get; set; }
        public Nullable<decimal> TIO2 { get; set; }
        public Nullable<decimal> R2 { get; set; }
        public Nullable<decimal> FEO { get; set; }
        public string RECORD_DATE { get; set; }
        public Nullable<decimal> TI6Z3 { get; set; }
        public Nullable<decimal> KMZS0Z5 { get; set; }
        public string TEAM { get; set; }
    }
}
