//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INSERT_DEVICE_FAULT
    {
        public Nullable<System.DateTime> FAULT_STARTTIME { get; set; }
        public string FAULT_NAME { get; set; }
        public string FAULT_MADEMAN { get; set; }
        public string ACCEPTANCE_MAN { get; set; }
        public Nullable<System.DateTime> ACCEPTANCE_TIME { get; set; }
        public Nullable<int> FAULT_ALLTIME { get; set; }
        public Nullable<System.DateTime> FAULT_ENDTIME { get; set; }
        public string RECORDER { get; set; }
        public string REMARK { get; set; }
        public string WP_NO { get; set; }
        public System.DateTime RECORD_DATE { get; set; }
        public string FLAG { get; set; }
    }
}
