//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MATERIAL_HOPPER_SUM
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> P1AI_401501F { get; set; }
        public Nullable<decimal> P1AI_401503F { get; set; }
        public Nullable<decimal> P1AI_401505F { get; set; }
        public Nullable<decimal> P1AI_401507F { get; set; }
        public Nullable<decimal> P1AI_401509F { get; set; }
        public Nullable<decimal> P1AI_401511F { get; set; }
        public Nullable<decimal> P1AI_401513F { get; set; }
        public Nullable<decimal> P1AI_401515F { get; set; }
        public Nullable<decimal> P1AI_401517F { get; set; }
        public Nullable<decimal> P1AI_401519F { get; set; }
        public Nullable<decimal> P1AI_401521F { get; set; }
        public Nullable<decimal> P1AI_401523F { get; set; }
        public Nullable<decimal> P1AI_401525F { get; set; }
        public Nullable<decimal> P1AI_401527F { get; set; }
        public Nullable<decimal> P1AI_401529F { get; set; }
        public Nullable<decimal> P1AI_401531F { get; set; }
        public Nullable<decimal> P1AI_401533F { get; set; }
        public Nullable<decimal> P1AI_401535F { get; set; }
        public Nullable<decimal> P1AI_401537F { get; set; }
        public Nullable<decimal> P1AI_401539F { get; set; }
        public Nullable<decimal> P1AI_401541F { get; set; }
        public Nullable<decimal> P1AI_401543F { get; set; }
        public Nullable<decimal> P2AI_408701F { get; set; }
    }
}
