//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MATERIAL_TEAM_YIELDGGL
    {
        public decimal RECORD_ID { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string WP_NO { get; set; }
        public string WP_NAME { get; set; }
        public Nullable<System.DateTime> TEAM_BEGIN_TIME { get; set; }
        public Nullable<System.DateTime> TEAM_END_TIME { get; set; }
        public Nullable<decimal> YIELD_SUM { get; set; }
        public string RECORD_NAME { get; set; }
        public string SHIFT { get; set; }
        public string TEAM { get; set; }
        public string FLAG { get; set; }
    }
}
