//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MATERIAL_METERING_MAP
    {
        public decimal MAP_ID { get; set; }
        public string DEVICE_NO { get; set; }
        public string DEVICE_NAME { get; set; }
        public string DEVICE_DESCR { get; set; }
        public string MAP_MAT_CODE { get; set; }
        public string MAP_MAT_NAME { get; set; }
        public Nullable<System.DateTime> MAP_BEGIN_TIME { get; set; }
        public Nullable<System.DateTime> MAP_END_TIME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATER { get; set; }
        public string MAP_STAT { get; set; }
    }
}
