//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MATERIAL_TEAM_YIELD
    {
        public Nullable<System.DateTime> TEAM_BEGIN_TIME { get; set; }
        public Nullable<System.DateTime> TEAM_END_TIME { get; set; }
        public string SHIFT { get; set; }
        public string TEAM { get; set; }
        public Nullable<decimal> YIELD_BEGIN { get; set; }
        public Nullable<decimal> YIELD_END { get; set; }
        public Nullable<decimal> YIELD_SUM { get; set; }
        public Nullable<decimal> RUN_TIME_MIN { get; set; }
        public Nullable<decimal> OPERATION_RATE { get; set; }
        public Nullable<decimal> TIME_YIELD { get; set; }
        public Nullable<decimal> OPERATING_FACTOR { get; set; }
        public decimal ID { get; set; }
    }
}
