//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class T_MATM : DbContext
    {
        public T_MATM()
            : base("name=T_MATM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_MATERIAL_SUPPLY> T_MATERIAL_SUPPLY { get; set; }
        public virtual DbSet<T_MATERIAL_HOPPER_SUM> T_MATERIAL_HOPPER_SUM { get; set; }
        public virtual DbSet<T_MATERIAL_METERING_MAP> T_MATERIAL_METERING_MAP { get; set; }
        public virtual DbSet<T_PRODUCE_SINTERING_RADIO> T_PRODUCE_SINTERING_RADIO { get; set; }
        public virtual DbSet<T_SINTER_MATERIAL_RATIO> T_SINTER_MATERIAL_RATIO { get; set; }
        public virtual DbSet<T_MATERIAL_TEAM_CONSUMPTION> T_MATERIAL_TEAM_CONSUMPTION { get; set; }
        public virtual DbSet<T_MATERIAL_TEAM_YIELD> T_MATERIAL_TEAM_YIELD { get; set; }
        public virtual DbSet<T_PRODUCE_SINTER_RUNSTOP> T_PRODUCE_SINTER_RUNSTOP { get; set; }
        public virtual DbSet<T_ENERGY_TEAM_CONSUMPTION> T_ENERGY_TEAM_CONSUMPTION { get; set; }
        public virtual DbSet<T_COST_TITLE_CONFIG> T_COST_TITLE_CONFIG { get; set; }
        public virtual DbSet<T_INSERT_QUAL_SJK> T_INSERT_QUAL_SJK { get; set; }
        public virtual DbSet<T_INSERT_DEVICE_FAULT> T_INSERT_DEVICE_FAULT { get; set; }
        public virtual DbSet<T_BASE_CODE> T_BASE_CODE { get; set; }
        public virtual DbSet<T_MATERIAL_TEAM_YIELD_FAL> T_MATERIAL_TEAM_YIELD_FAL { get; set; }
    
        public virtual int F_QUALITY_QUARY(string mATERIAL_NAME, string bEGIN_TIME, string eND_TIME, string sAMPLE_NO, string lU_NO)
        {
            var mATERIAL_NAMEParameter = mATERIAL_NAME != null ?
                new ObjectParameter("MATERIAL_NAME", mATERIAL_NAME) :
                new ObjectParameter("MATERIAL_NAME", typeof(string));
    
            var bEGIN_TIMEParameter = bEGIN_TIME != null ?
                new ObjectParameter("BEGIN_TIME", bEGIN_TIME) :
                new ObjectParameter("BEGIN_TIME", typeof(string));
    
            var eND_TIMEParameter = eND_TIME != null ?
                new ObjectParameter("END_TIME", eND_TIME) :
                new ObjectParameter("END_TIME", typeof(string));
    
            var sAMPLE_NOParameter = sAMPLE_NO != null ?
                new ObjectParameter("SAMPLE_NO", sAMPLE_NO) :
                new ObjectParameter("SAMPLE_NO", typeof(string));
    
            var lU_NOParameter = lU_NO != null ?
                new ObjectParameter("LU_NO", lU_NO) :
                new ObjectParameter("LU_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("F_QUALITY_QUARY", mATERIAL_NAMEParameter, bEGIN_TIMEParameter, eND_TIMEParameter, sAMPLE_NOParameter, lU_NOParameter);
        }
    }
}
