//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MATERIAL_SUPPLY
    {
        public string WORK_TIME { get; set; }
        public string MAT_BATCH_NO { get; set; }
        public string MAT_PROD_CODE { get; set; }
        public string MAT_PROD_CNAME { get; set; }
        public string RUB_TAPE_START_TIME { get; set; }
        public string RUB_TAPE_END_TIME { get; set; }
        public Nullable<decimal> CARRY_WGT { get; set; }
        public string SRC_PILE_NO { get; set; }
        public string DST_PILE_NO { get; set; }
        public string BACKLOG_CODE { get; set; }
        public string SCALE_NO { get; set; }
        public string NOTICE_NO { get; set; }
        public string WEIGH_BY { get; set; }
        public string MAT_TRANS_TYPE { get; set; }
        public string CONFIRM_MAN { get; set; }
        public Nullable<System.DateTime> CONFIRM_TIME { get; set; }
        public string REMARK { get; set; }
        public string BIN_COLLECTION { get; set; }
    }
}
