//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MATERIAL_RADIO_REMARK
    {
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string PBD_NO { get; set; }
        public string RECORD_PERSON { get; set; }
        public string MATERIAL1 { get; set; }
        public string PERCENT1 { get; set; }
        public string MATERIAL2 { get; set; }
        public string PERCENT2 { get; set; }
        public string MATERIAL3 { get; set; }
        public string PERCENT3 { get; set; }
        public string MATERIAL4 { get; set; }
        public string PERCENT4 { get; set; }
        public string MATERIAL5 { get; set; }
        public string PERCENT5 { get; set; }
        public string MATERIAL6 { get; set; }
        public string PERCENT6 { get; set; }
        public string MATERIAL7 { get; set; }
        public string PERCENT7 { get; set; }
        public string MATERIAL8 { get; set; }
        public string PERCENT8 { get; set; }
        public string MATERIAL9 { get; set; }
        public string PERCENT9 { get; set; }
        public string REMARK { get; set; }
    }
}
