//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_SINTERING_RADIO
    {
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public Nullable<decimal> P1AO_401801F { get; set; }
        public Nullable<decimal> P1AO_401803F { get; set; }
        public Nullable<decimal> P1AO_401805F { get; set; }
        public Nullable<decimal> P1AO_401807F { get; set; }
        public Nullable<decimal> P1AO_401809F { get; set; }
        public Nullable<decimal> P1AO_401811F { get; set; }
        public Nullable<decimal> P1AO_401813F { get; set; }
        public Nullable<decimal> P1AO_401815F { get; set; }
        public Nullable<decimal> P1AO_401817F { get; set; }
        public Nullable<decimal> P1AO_401819F { get; set; }
        public Nullable<decimal> P1AO_401821F { get; set; }
        public Nullable<decimal> P1AO_401823F { get; set; }
        public Nullable<decimal> P1AO_401825F { get; set; }
        public Nullable<decimal> P1AO_401827F { get; set; }
        public Nullable<decimal> P1AO_401829F { get; set; }
        public Nullable<decimal> P1AO_401831F { get; set; }
        public Nullable<decimal> P1AO_401833F { get; set; }
        public Nullable<decimal> P1AO_401835F { get; set; }
        public Nullable<decimal> P1AO_401837F { get; set; }
        public Nullable<decimal> P1AO_401839F { get; set; }
        public decimal HOPPER_ID { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
    }
}
