//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_TUOLIU_CEMS
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> RK_DYHW_NOX { get; set; }
        public Nullable<decimal> CK_DYHW_NOX { get; set; }
        public Nullable<decimal> RK_SO2 { get; set; }
        public Nullable<decimal> CK_SO2 { get; set; }
        public Nullable<decimal> RK_FC { get; set; }
        public Nullable<decimal> CK_FC { get; set; }
        public Nullable<decimal> RK_YQHL { get; set; }
        public Nullable<decimal> CK_YQHL { get; set; }
        public Nullable<decimal> RK_SD { get; set; }
        public Nullable<decimal> CK_SD { get; set; }
        public Nullable<decimal> RK_LL { get; set; }
        public Nullable<decimal> CK_LL { get; set; }
        public Nullable<decimal> RK_YQWD { get; set; }
        public Nullable<decimal> CK_YQWD { get; set; }
        public Nullable<decimal> RK_YL { get; set; }
        public Nullable<decimal> CK_YL { get; set; }
        public Nullable<decimal> NOX_CY { get; set; }
        public Nullable<decimal> SO2_CY { get; set; }
        public Nullable<decimal> DUST_CY { get; set; }
        public Nullable<decimal> QHR_VALUE { get; set; }
        public Nullable<decimal> NOX_C { get; set; }
        public Nullable<decimal> SO2_C { get; set; }
        public Nullable<decimal> DUST_C { get; set; }
        public Nullable<decimal> CMS_DUST1 { get; set; }
        public Nullable<decimal> CMS_DUST2 { get; set; }
        public Nullable<decimal> CMS_DUST3 { get; set; }
    }
}
