//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_OPERATIONAL_LOG
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> P3AI_401071F { get; set; }
        public Nullable<decimal> P3AI_401081F { get; set; }
        public Nullable<decimal> P3AI_401091F { get; set; }
        public Nullable<decimal> P3AI_401101F { get; set; }
        public Nullable<decimal> P3AI_401111F { get; set; }
        public Nullable<decimal> P3AI_401121F { get; set; }
        public Nullable<decimal> P3AI_401131F { get; set; }
        public Nullable<decimal> P3AI_401141F { get; set; }
        public Nullable<decimal> P3AI_401151F { get; set; }
        public Nullable<decimal> P3AI_401161F { get; set; }
        public Nullable<decimal> P3AI_401171F { get; set; }
        public Nullable<decimal> P3AI_401301F { get; set; }
        public Nullable<decimal> P3AI_401361F { get; set; }
        public Nullable<decimal> P3AI_401761F { get; set; }
        public Nullable<decimal> P3AI_401771F { get; set; }
        public Nullable<decimal> P3AI_402331F { get; set; }
        public Nullable<decimal> P3AI_402341F { get; set; }
        public Nullable<decimal> PLCNYAI_406002F { get; set; }
        public Nullable<decimal> PLCNYAI_406012F { get; set; }
        public Nullable<decimal> PLCNYAI_406022F { get; set; }
        public Nullable<decimal> PLCNYAI_406032F { get; set; }
        public Nullable<decimal> PLCNYAI_406042F { get; set; }
        public Nullable<decimal> PLCNYAI_406052F { get; set; }
        public Nullable<decimal> PLCNYAI_406004F { get; set; }
        public Nullable<decimal> PLCNYAI_406014F { get; set; }
        public Nullable<decimal> PLCNYAI_406024F { get; set; }
        public Nullable<decimal> PLCNYAI_406034F { get; set; }
        public Nullable<decimal> PLCNYAI_406044F { get; set; }
        public Nullable<decimal> PLCNYAI_406054F { get; set; }
        public Nullable<decimal> P3AI_401331F { get; set; }
        public Nullable<decimal> P3AI_401341F { get; set; }
        public Nullable<decimal> P3AI_401351F { get; set; }
        public Nullable<decimal> P3AI_401951F { get; set; }
        public Nullable<decimal> P3AI_401961F { get; set; }
        public Nullable<decimal> P3AI_405317F { get; set; }
        public Nullable<decimal> P3AI_401011F { get; set; }
        public Nullable<decimal> P3AI_401021F { get; set; }
        public Nullable<decimal> P3AI_401031F { get; set; }
        public Nullable<decimal> P3AI_401041F { get; set; }
        public Nullable<decimal> P3AI_401051F { get; set; }
        public Nullable<decimal> P3AI_401061F { get; set; }
        public Nullable<decimal> P3AI_400961F { get; set; }
        public Nullable<decimal> P3AI_400971F { get; set; }
    }
}
