//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_BELLOWS_PRESSURE
    {
        public System.DateTime DATE_ID { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE1 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE2 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE3 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE4 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE5 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE6 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE7 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE8 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE9 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE10 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE11 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE12 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE13 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE14 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE15 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE16 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE17 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE18 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE19 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE20 { get; set; }
        public Nullable<decimal> BELLOWS_PRESSURE21 { get; set; }
        public string TEAM { get; set; }
        public string SHIFTS { get; set; }
        public string ROW_DESCRIBE { get; set; }
    }
}
