//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_FEEDING_INSTRUCTIONS
    {
        public string INSTRUCTIONS_NO { get; set; }
        public string OPERATION_AREA { get; set; }
        public Nullable<System.DateTime> FEEDING_DATE { get; set; }
        public string FEEDING_KIND { get; set; }
        public string SENDING_PERSON { get; set; }
        public Nullable<System.DateTime> SENDING_DATE { get; set; }
        public string REMARK { get; set; }
        public string WHETHER_CONFIRMED { get; set; }
        public string CONFIRMED_PERSON { get; set; }
        public Nullable<System.DateTime> CONFIRMED_DATE { get; set; }
        public string FEEDING_CHOOSE { get; set; }
    }
}
