//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class T_PROM : DbContext
    {
        public T_PROM()
            : base("name=T_PROM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_PRODUCE_FEEDING_INSTRUCTIONS> T_PRODUCE_FEEDING_INSTRUCTIONS { get; set; }
        public virtual DbSet<T_QUALITY_MIX_PHY_INSET> T_QUALITY_MIX_PHY_INSET { get; set; }
        public virtual DbSet<T_INSERT_CHANGE_SHIFT> T_INSERT_CHANGE_SHIFT { get; set; }
        public virtual DbSet<T_INSERT_DEVICE_FAULT> T_INSERT_DEVICE_FAULT { get; set; }
        public virtual DbSet<T_PRODUCE_BELLOWS_PRESSURE> T_PRODUCE_BELLOWS_PRESSURE { get; set; }
        public virtual DbSet<T_PRODUCE_BELLOWS_TEMPERATURE> T_PRODUCE_BELLOWS_TEMPERATURE { get; set; }
        public virtual DbSet<T_PRODUCE_MIX_DEVICE> T_PRODUCE_MIX_DEVICE { get; set; }
        public virtual DbSet<T_BASE_MATERIAL> T_BASE_MATERIAL { get; set; }
        public virtual DbSet<T_PRODUCE_HOPPER_POSITION> T_PRODUCE_HOPPER_POSITION { get; set; }
        public virtual DbSet<T_PRODUCE_MAIN_EXHAUST_FAN> T_PRODUCE_MAIN_EXHAUST_FAN { get; set; }
        public virtual DbSet<T_PRODUCE_OPERATIONAL_TEMP_LOG> T_PRODUCE_OPERATIONAL_TEMP_LOG { get; set; }
        public virtual DbSet<T_PRODUCE_TUOLIU_AZ> T_PRODUCE_TUOLIU_AZ { get; set; }
        public virtual DbSet<T_PRODUCE_TUOLIU_CEMS> T_PRODUCE_TUOLIU_CEMS { get; set; }
        public virtual DbSet<T_PRODUCE_TUOLIU_NYJZ> T_PRODUCE_TUOLIU_NYJZ { get; set; }
        public virtual DbSet<T_PRODUCE_TUOLIU_ZYFJ> T_PRODUCE_TUOLIU_ZYFJ { get; set; }
        public virtual DbSet<T_ENERGY_CONSUME> T_ENERGY_CONSUME { get; set; }
        public virtual DbSet<T_PRODUCE_SINTER_SCRB_CENTER> T_PRODUCE_SINTER_SCRB_CENTER { get; set; }
        public virtual DbSet<T_PRODUCE_OPERATIONAL_LOG> T_PRODUCE_OPERATIONAL_LOG { get; set; }
        public virtual DbSet<T_MATERIAL_TEAM_YIELDGGL> T_MATERIAL_TEAM_YIELDGGL { get; set; }
        public virtual DbSet<T_PRODUCE_MAIN_EXHAUST_DH> T_PRODUCE_MAIN_EXHAUST_DH { get; set; }
        public virtual DbSet<T_PRODUCE_GAOLULC> T_PRODUCE_GAOLULC { get; set; }
        public virtual DbSet<T_PRODUCE_YANDAOXUNHUAN> T_PRODUCE_YANDAOXUNHUAN { get; set; }
        public virtual DbSet<T_PRODUCE_SINTER_SCRB> T_PRODUCE_SINTER_SCRB { get; set; }
        public virtual DbSet<T_PRODUCE_SINTER_SCRB1> T_PRODUCE_SINTER_SCRB1 { get; set; }
        public virtual DbSet<T_PRODUCE_SINTER_SCRB2> T_PRODUCE_SINTER_SCRB2 { get; set; }
        public virtual DbSet<T_MATERIAL_RADIO_REMARK> T_MATERIAL_RADIO_REMARK { get; set; }
    
        public virtual int F_QUAITY_ANALYSE(string mATERIAL_NAME, string bEGIN_TIME, string eND_TIME)
        {
            var mATERIAL_NAMEParameter = mATERIAL_NAME != null ?
                new ObjectParameter("MATERIAL_NAME", mATERIAL_NAME) :
                new ObjectParameter("MATERIAL_NAME", typeof(string));
    
            var bEGIN_TIMEParameter = bEGIN_TIME != null ?
                new ObjectParameter("BEGIN_TIME", bEGIN_TIME) :
                new ObjectParameter("BEGIN_TIME", typeof(string));
    
            var eND_TIMEParameter = eND_TIME != null ?
                new ObjectParameter("END_TIME", eND_TIME) :
                new ObjectParameter("END_TIME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("F_QUAITY_ANALYSE", mATERIAL_NAMEParameter, bEGIN_TIMEParameter, eND_TIMEParameter);
        }
    
        public virtual ObjectResult<System.Data.Entity.Spatial.DbGeography> F_QUAITY_ANALYSE1(string mATERIAL_NAME, string bEGIN_TIME, string eND_TIME, string sAMPLE_NO)
        {
            var mATERIAL_NAMEParameter = mATERIAL_NAME != null ?
                new ObjectParameter("MATERIAL_NAME", mATERIAL_NAME) :
                new ObjectParameter("MATERIAL_NAME", typeof(string));
    
            var bEGIN_TIMEParameter = bEGIN_TIME != null ?
                new ObjectParameter("BEGIN_TIME", bEGIN_TIME) :
                new ObjectParameter("BEGIN_TIME", typeof(string));
    
            var eND_TIMEParameter = eND_TIME != null ?
                new ObjectParameter("END_TIME", eND_TIME) :
                new ObjectParameter("END_TIME", typeof(string));
    
            var sAMPLE_NOParameter = sAMPLE_NO != null ?
                new ObjectParameter("SAMPLE_NO", sAMPLE_NO) :
                new ObjectParameter("SAMPLE_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<System.Data.Entity.Spatial.DbGeography>("F_QUAITY_ANALYSE1", mATERIAL_NAMEParameter, bEGIN_TIMEParameter, eND_TIMEParameter, sAMPLE_NOParameter);
        }
    
        public virtual int F_QUALITY_QUARY(string mATERIAL_NAME, string bEGIN_TIME, string eND_TIME, string sAMPLE_NO, string lU_NO)
        {
            var mATERIAL_NAMEParameter = mATERIAL_NAME != null ?
                new ObjectParameter("MATERIAL_NAME", mATERIAL_NAME) :
                new ObjectParameter("MATERIAL_NAME", typeof(string));
    
            var bEGIN_TIMEParameter = bEGIN_TIME != null ?
                new ObjectParameter("BEGIN_TIME", bEGIN_TIME) :
                new ObjectParameter("BEGIN_TIME", typeof(string));
    
            var eND_TIMEParameter = eND_TIME != null ?
                new ObjectParameter("END_TIME", eND_TIME) :
                new ObjectParameter("END_TIME", typeof(string));
    
            var sAMPLE_NOParameter = sAMPLE_NO != null ?
                new ObjectParameter("SAMPLE_NO", sAMPLE_NO) :
                new ObjectParameter("SAMPLE_NO", typeof(string));
    
            var lU_NOParameter = lU_NO != null ?
                new ObjectParameter("LU_NO", lU_NO) :
                new ObjectParameter("LU_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("F_QUALITY_QUARY", mATERIAL_NAMEParameter, bEGIN_TIMEParameter, eND_TIMEParameter, sAMPLE_NOParameter, lU_NOParameter);
        }
    }
}
