//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_TUOLIU_NYJZ
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> NYJZ_ASSSLL { get; set; }
        public Nullable<decimal> NYJZ_ASLJLL { get; set; }
        public Nullable<decimal> NYJZ_RHSSSLL { get; set; }
        public Nullable<decimal> NYJZ_RHSLJLL { get; set; }
        public Nullable<decimal> NYJZ_ZQSSLL { get; set; }
        public Nullable<decimal> NYJZ_FQCKSSLL { get; set; }
        public Nullable<decimal> NYJZ_FQCKLJLL { get; set; }
        public Nullable<decimal> NYJZ_DQZGSSLL { get; set; }
        public Nullable<decimal> NYJZ_YSKQSSLL { get; set; }
        public Nullable<decimal> NYJZ_XHSSSLL { get; set; }
        public Nullable<decimal> NYJZ_XHSLJLL { get; set; }
        public Nullable<decimal> NYJZ_TRQSSLL { get; set; }
        public Nullable<decimal> NYJZ_TRQLJLL { get; set; }
        public Nullable<decimal> NYJZ_GLMQSSLL { get; set; }
        public Nullable<decimal> NYJZ_GLMQLJLL { get; set; }
    }
}
