//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_OPERATIONAL_TEMP_LOG
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> P3AI_400011F { get; set; }
        public Nullable<decimal> P3AI_400021F { get; set; }
        public Nullable<decimal> P3AI_400051F { get; set; }
        public Nullable<decimal> P3AI_400061F { get; set; }
        public Nullable<decimal> PLCNYAI_406000F { get; set; }
        public Nullable<decimal> PLCNYAI_406010F { get; set; }
        public Nullable<decimal> PLCNYAI_406020F { get; set; }
        public Nullable<decimal> PLCNYAI_406030F { get; set; }
        public Nullable<decimal> PLCNYAI_406040F { get; set; }
        public Nullable<decimal> PLCNYAI_406050F { get; set; }
        public Nullable<decimal> P3AI_400521F { get; set; }
        public Nullable<decimal> P3AI_400531F { get; set; }
        public Nullable<decimal> P3AI_401291F { get; set; }
        public Nullable<decimal> P3AI_401791F { get; set; }
        public Nullable<decimal> P3AI_402921F { get; set; }
        public Nullable<decimal> P3AI_402931F { get; set; }
        public Nullable<decimal> P3AI_402941F { get; set; }
        public Nullable<decimal> P3AI_402951F { get; set; }
        public Nullable<decimal> P3AI_402961F { get; set; }
    }
}
