//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_MAIN_EXHAUST_FAN
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> P4AI_400011F { get; set; }
        public Nullable<decimal> P4AI_400021F { get; set; }
        public Nullable<decimal> P4AI_400031F { get; set; }
        public Nullable<decimal> P4AI_400041F { get; set; }
        public Nullable<decimal> P4AI_400051F { get; set; }
        public Nullable<decimal> P4AI_400061F { get; set; }
        public Nullable<decimal> P4AI_400071F { get; set; }
        public Nullable<decimal> P4AI_400081F { get; set; }
        public Nullable<decimal> P4AI_400091F { get; set; }
        public Nullable<decimal> P4AI_400101F { get; set; }
        public Nullable<decimal> P4AI_400111F { get; set; }
        public Nullable<decimal> P4AI_400121F { get; set; }
        public Nullable<decimal> P4AI_400131F { get; set; }
        public Nullable<decimal> P4AI_400141F { get; set; }
        public Nullable<decimal> P4AI_400151F { get; set; }
        public Nullable<decimal> P4AI_400161F { get; set; }
        public Nullable<decimal> P4AI_400171F { get; set; }
        public Nullable<decimal> P4AI_400181F { get; set; }
        public Nullable<decimal> P4AI_400191F { get; set; }
        public Nullable<decimal> P4AI_400201F { get; set; }
        public Nullable<decimal> P4AI_400211F { get; set; }
        public Nullable<decimal> P4AI_400221F { get; set; }
        public Nullable<decimal> P4AI_400231F { get; set; }
        public Nullable<decimal> P4AI_400241F { get; set; }
        public Nullable<decimal> P4AI_400251F { get; set; }
        public Nullable<decimal> P4AI_400261F { get; set; }
        public Nullable<decimal> P4AI_400271F { get; set; }
        public Nullable<decimal> P4AI_400281F { get; set; }
        public Nullable<decimal> P4AI_400291F { get; set; }
        public Nullable<decimal> P4AI_400301F { get; set; }
        public Nullable<decimal> P4AI_400311F { get; set; }
        public Nullable<decimal> P4AI_400321F { get; set; }
        public Nullable<decimal> P4AI_400331F { get; set; }
        public Nullable<decimal> P4AI_400341F { get; set; }
        public Nullable<decimal> P4AI_400351F { get; set; }
        public Nullable<decimal> P4AI_400361F { get; set; }
        public Nullable<decimal> P4AI_400371F { get; set; }
        public Nullable<decimal> P4AI_400381F { get; set; }
        public Nullable<decimal> P4AI_400391F { get; set; }
        public Nullable<decimal> P4AI_400401F { get; set; }
        public Nullable<decimal> P4AI_400411F { get; set; }
        public Nullable<decimal> P4AI_400421F { get; set; }
        public Nullable<decimal> P4AI_400431F { get; set; }
        public Nullable<decimal> P4AI_400441F { get; set; }
        public Nullable<decimal> P4AI_400451F { get; set; }
        public Nullable<decimal> P4AI_400461F { get; set; }
        public Nullable<decimal> P4AI_400471F { get; set; }
        public Nullable<decimal> P4AI_400481F { get; set; }
        public Nullable<decimal> P4AI_400491F { get; set; }
        public Nullable<decimal> P4AI_400501F { get; set; }
        public Nullable<decimal> P4AI_400511F { get; set; }
        public Nullable<decimal> P4AI_400521F { get; set; }
        public Nullable<decimal> P4AI_400531F { get; set; }
        public Nullable<decimal> P4AI_400541F { get; set; }
        public Nullable<decimal> P4AI_400551F { get; set; }
        public Nullable<decimal> P4AI_400561F { get; set; }
        public Nullable<decimal> P4AI_400571F { get; set; }
        public Nullable<decimal> P4AI_400581F { get; set; }
        public Nullable<decimal> P4AI_400591F { get; set; }
        public Nullable<decimal> P4AI_400601F { get; set; }
        public Nullable<decimal> P4AI_400611F { get; set; }
        public Nullable<decimal> P4AI_400621F { get; set; }
        public Nullable<decimal> P4AI_400631F { get; set; }
        public Nullable<decimal> P4AI_400641F { get; set; }
        public Nullable<decimal> P4AI_400651F { get; set; }
        public Nullable<decimal> P4AI_400661F { get; set; }
        public Nullable<decimal> P4AI_400671F { get; set; }
        public Nullable<decimal> P4AI_400681F { get; set; }
        public Nullable<decimal> P4AI_400691F { get; set; }
        public Nullable<decimal> P4AI_400701F { get; set; }
        public Nullable<decimal> P4AI_400711F { get; set; }
        public Nullable<decimal> P4AI_400721F { get; set; }
        public Nullable<decimal> P4AI_400731F { get; set; }
        public Nullable<decimal> P4AI_400741F { get; set; }
        public Nullable<decimal> P4AI_400751F { get; set; }
        public Nullable<decimal> P4AI_400761F { get; set; }
        public Nullable<decimal> P4AI_400771F { get; set; }
        public Nullable<decimal> P4AI_400781F { get; set; }
        public Nullable<decimal> P4AI_400791F { get; set; }
        public Nullable<decimal> P4AI_400801F { get; set; }
        public Nullable<decimal> P4AI_400811F { get; set; }
        public Nullable<decimal> P4AI_400821F { get; set; }
        public Nullable<decimal> P4AI_400831F { get; set; }
        public Nullable<decimal> P4AI_400841F { get; set; }
        public Nullable<decimal> P4AI_400851F { get; set; }
        public Nullable<decimal> P4AI_400861F { get; set; }
        public Nullable<decimal> P4AI_400871F { get; set; }
        public Nullable<decimal> P4AI_400881F { get; set; }
        public Nullable<decimal> P4AI_400891F { get; set; }
        public Nullable<decimal> P4AI_400901F { get; set; }
        public Nullable<decimal> P4AI_400911F { get; set; }
        public Nullable<decimal> P4AI_400921F { get; set; }
        public Nullable<decimal> P4AI_400931F { get; set; }
        public Nullable<decimal> P4AI_400941F { get; set; }
        public Nullable<decimal> P4AI_400951F { get; set; }
        public Nullable<decimal> P4AI_400961F { get; set; }
        public Nullable<decimal> P4AI_400971F { get; set; }
        public Nullable<decimal> P4AI_401611F { get; set; }
        public Nullable<decimal> P4AI_401621F { get; set; }
    }
}
