//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_SINTER_SCRB1
    {
        public decimal RECORD_ID { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string TEAM { get; set; }
        public Nullable<decimal> LCHD { get; set; }
        public Nullable<decimal> JS { get; set; }
        public Nullable<decimal> DYDFY { get; set; }
        public Nullable<decimal> FQWD { get; set; }
        public Nullable<decimal> KQWD { get; set; }
        public Nullable<decimal> DHWD { get; set; }
        public Nullable<decimal> LTFY { get; set; }
        public Nullable<decimal> MQYL { get; set; }
        public Nullable<decimal> KQYL { get; set; }
        public Nullable<decimal> YHSF { get; set; }
        public Nullable<decimal> EHSF { get; set; }
        public Nullable<decimal> EHLW { get; set; }
        public Nullable<decimal> ERLD { get; set; }
        public Nullable<decimal> RL_3M { get; set; }
        public Nullable<decimal> RL_H2O { get; set; }
        public Nullable<decimal> GTRH { get; set; }
        public Nullable<decimal> GLMQXH { get; set; }
        public Nullable<decimal> TRQXH { get; set; }
        public Nullable<decimal> DH { get; set; }
        public Nullable<decimal> HL_SO2 { get; set; }
        public Nullable<decimal> HL_NO { get; set; }
        public Nullable<decimal> HL_FC { get; set; }
        public Nullable<decimal> DH_CO { get; set; }
        public Nullable<decimal> YQYL_1_AVG { get; set; }
        public Nullable<decimal> YQYL_2_AVG { get; set; }
        public string SHIFT { get; set; }
        public Nullable<decimal> ZYDWD_AVG { get; set; }
        public Nullable<decimal> YYDWD_AVG { get; set; }
    }
}
