//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_HOPPER_POSITION
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> P1AI_400001F { get; set; }
        public Nullable<decimal> P1AI_400011F { get; set; }
        public Nullable<decimal> P1AI_400021F { get; set; }
        public Nullable<decimal> P1AI_400031F { get; set; }
        public Nullable<decimal> P1AI_400041F { get; set; }
        public Nullable<decimal> P1AI_400051F { get; set; }
        public Nullable<decimal> P1AI_400061F { get; set; }
        public Nullable<decimal> P1AI_400071F { get; set; }
        public Nullable<decimal> P1AI_400081F { get; set; }
        public Nullable<decimal> P1AI_400091F { get; set; }
        public Nullable<decimal> P1AI_400101F { get; set; }
        public Nullable<decimal> P1AI_400111F { get; set; }
        public Nullable<decimal> P1AI_400121F { get; set; }
        public Nullable<decimal> P1AI_400131F { get; set; }
        public Nullable<decimal> P1AI_400141F { get; set; }
        public Nullable<decimal> P1AI_400291F { get; set; }
        public Nullable<decimal> P1AI_400601F { get; set; }
        public Nullable<decimal> P1AI_400611F { get; set; }
        public Nullable<decimal> P1AI_400621F { get; set; }
        public Nullable<decimal> P1AI_400631F { get; set; }
        public Nullable<decimal> P3AI_401141F { get; set; }
        public Nullable<decimal> P3AI_401151F { get; set; }
        public Nullable<decimal> P3AI_401891F { get; set; }
        public Nullable<decimal> P3AI_401901F { get; set; }
        public string TAEM { get; set; }
    }
}
