//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_BELLOWS_TEMPERATURE
    {
        public System.DateTime DATE_ID { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE1 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE2 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE3 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE4 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE5 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE6 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE7 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE8 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE9 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE10 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE11 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE12 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE13 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE14 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE15 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE16 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE17 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE18 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE19 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE20 { get; set; }
        public Nullable<decimal> BELLOWS_TEMPERATURE21 { get; set; }
        public string TEAM { get; set; }
        public string SHIFTS { get; set; }
        public string ROW_DESCRIBE { get; set; }
    }
}
