//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_YANDAOXUNHUAN
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> PLCYDXHAI_400567F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400569F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400571F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400573F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400575F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400577F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400619F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400621F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400623F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400625F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400627F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400629F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400541F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400543F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400545F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400547F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400549F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400551F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400861F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400609F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400529F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400531F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400509F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400511F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400563F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400555F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400611F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400533F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400613F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400605F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400535F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400537F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400525F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400527F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400565F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400615F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400557F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400617F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400539F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400559F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400579F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400581F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400583F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400585F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400587F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400589F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400591F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400593F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400595F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400597F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400599F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400601F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400603F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400417F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400419F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400421F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400423F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400425F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400427F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400429F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400433F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400435F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400437F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400439F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400441F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400443F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400497F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400499F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400501F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400503F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400505F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400507F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400513F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400515F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400517F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400519F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400521F { get; set; }
        public Nullable<decimal> PLCYDXHAI_400523F { get; set; }
    }
}
