//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_GAOLULC
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> GL1_LC_SJ1 { get; set; }
        public Nullable<decimal> GL1_LC_SJ2 { get; set; }
        public Nullable<decimal> GL1_LC_SJ3 { get; set; }
        public Nullable<decimal> GL1_LC_SJ4 { get; set; }
        public Nullable<decimal> GL1_LC_SJ5 { get; set; }
        public Nullable<decimal> GL1_LC_SJ6 { get; set; }
        public Nullable<decimal> GL1_LC_SJ7 { get; set; }
        public Nullable<decimal> GL1_LC_SJ8 { get; set; }
        public Nullable<decimal> GL1_LC_SJ9 { get; set; }
        public Nullable<decimal> GL1_LC_SJ10 { get; set; }
        public Nullable<decimal> GL2_LC_SJ1 { get; set; }
        public Nullable<decimal> GL2_LC_SJ2 { get; set; }
        public Nullable<decimal> GL2_LC_SJ3 { get; set; }
        public Nullable<decimal> GL2_LC_SJ4 { get; set; }
        public Nullable<decimal> GL2_LC_SJ5 { get; set; }
        public Nullable<decimal> GL2_LC_SJ6 { get; set; }
        public Nullable<decimal> GL2_LC_SJ7 { get; set; }
        public Nullable<decimal> GL2_LC_SJ8 { get; set; }
        public Nullable<decimal> GL2_LC_SJ9 { get; set; }
        public Nullable<decimal> GL2_LC_SJ10 { get; set; }
        public Nullable<decimal> T6_LC_SJ1 { get; set; }
        public Nullable<decimal> T6_LC_SJ2 { get; set; }
        public Nullable<decimal> T6_LC_SJ3 { get; set; }
        public Nullable<decimal> T6_LC_SJ4 { get; set; }
        public Nullable<decimal> T6_LC_SJ5 { get; set; }
        public Nullable<decimal> GL1_AVG { get; set; }
        public Nullable<decimal> GL2_AVG { get; set; }
        public Nullable<decimal> T6_AVG { get; set; }
        public Nullable<decimal> T7_AVG { get; set; }
        public Nullable<decimal> T7_LC_SJ1 { get; set; }
        public Nullable<decimal> T7_LC_SJ2 { get; set; }
        public Nullable<decimal> T7_LC_SJ3 { get; set; }
        public Nullable<decimal> T7_LC_SJ4 { get; set; }
        public Nullable<decimal> T7_LC_SJ5 { get; set; }
        public Nullable<decimal> T7_LC_SJ6 { get; set; }
        public Nullable<decimal> T7_LC_SJ7 { get; set; }
        public Nullable<decimal> T7_LC_SJ8 { get; set; }
        public Nullable<decimal> T7_LC_SJ9 { get; set; }
        public Nullable<decimal> T7_LC_SJ10 { get; set; }
    }
}
