//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_SINTER_SCRB_CENTER
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> FEO_CENTER { get; set; }
        public Nullable<decimal> R_CENTER { get; set; }
    }
}
