//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_SINTER_SCRB2
    {
        public decimal RECORD_ID { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string TEAM { get; set; }
        public Nullable<decimal> PISHU { get; set; }
        public Nullable<decimal> TFE { get; set; }
        public Nullable<decimal> FEO { get; set; }
        public Nullable<decimal> SIO2 { get; set; }
        public Nullable<decimal> CAO { get; set; }
        public Nullable<decimal> MGO { get; set; }
        public Nullable<decimal> AL2O3 { get; set; }
        public Nullable<decimal> R { get; set; }
        public Nullable<decimal> TI6Z3 { get; set; }
        public Nullable<decimal> KMZS0Z5 { get; set; }
        public Nullable<decimal> JIANXIU { get; set; }
        public Nullable<decimal> JIXIE { get; set; }
        public Nullable<decimal> DIANQI { get; set; }
        public Nullable<decimal> CAOZUO { get; set; }
        public Nullable<decimal> YLC { get; set; }
        public Nullable<decimal> GAOLU { get; set; }
        public Nullable<decimal> DONGLI { get; set; }
        public Nullable<decimal> QTWY { get; set; }
        public Nullable<decimal> ZYSJ_DAY { get; set; }
        public Nullable<decimal> ZYSJ_SUM { get; set; }
        public Nullable<decimal> ZYL_DAY { get; set; }
        public Nullable<decimal> ZYL_SUM { get; set; }
        public string SHIFT { get; set; }
    }
}
