//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_TUOLIU_ZYFJ
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> CW_ZYFJ_DJDZ3_WD { get; set; }
        public Nullable<decimal> CW_ZYFJ_DJZC1_WD { get; set; }
        public Nullable<decimal> CW_ZYFJ_WD { get; set; }
        public Nullable<decimal> CW_ZYFJ_FJZD { get; set; }
        public Nullable<decimal> CW_ZYFJ_DJZD { get; set; }
        public Nullable<decimal> CW_ZYFJ_DJDL { get; set; }
        public Nullable<decimal> CW_ZYFJ_TJF_KD { get; set; }
        public Nullable<decimal> CW_ZYFJ_TJF_SKD { get; set; }
        public Nullable<decimal> CW_XTWD_HRQJKYQWD_A { get; set; }
        public Nullable<decimal> CW_XTWD_HRQCKYQWD_A { get; set; }
        public Nullable<decimal> CW_XTWD_ZYFJCKWD1_A { get; set; }
        public Nullable<decimal> CW_XTWD_ZYFJCKWD2_A { get; set; }
        public Nullable<decimal> CW_XTWD_HRQJKYQWD_B { get; set; }
        public Nullable<decimal> CW_XTWD_HRQCKYQWD_B { get; set; }
        public Nullable<decimal> CW_XTWD_ZYFJCKWD1_B { get; set; }
        public Nullable<decimal> CW_XTWD_ZYFJCKWD2_B { get; set; }
    }
}
