//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_SINTER_SCRB
    {
        public decimal RECORD_ID { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string TEAM { get; set; }
        public Nullable<decimal> CL_DAY { get; set; }
        public Nullable<decimal> CL_SUM { get; set; }
        public Nullable<decimal> XS_DAY { get; set; }
        public Nullable<decimal> XS_SUM { get; set; }
        public Nullable<decimal> TSCL_DAY { get; set; }
        public Nullable<decimal> TSCL_SUM { get; set; }
        public Nullable<decimal> ZQCL_DAY { get; set; }
        public Nullable<decimal> ZQCL_SUM { get; set; }
        public Nullable<decimal> FKL_DAY { get; set; }
        public Nullable<decimal> FKL_SUM { get; set; }
        public Nullable<decimal> CKL_DAY { get; set; }
        public Nullable<decimal> CKL_SUM { get; set; }
        public Nullable<decimal> RLTS_DAY { get; set; }
        public Nullable<decimal> RLTS_SUM { get; set; }
        public Nullable<decimal> FEO_WDL_DAY { get; set; }
        public Nullable<decimal> FEO_WDL_SUM { get; set; }
        public Nullable<decimal> R_WDL_DAY { get; set; }
        public Nullable<decimal> R_WDL_SUM { get; set; }
        public Nullable<decimal> YJPL_DAY { get; set; }
        public Nullable<decimal> YJPL_SUM { get; set; }
        public Nullable<decimal> YZPL_DAY { get; set; }
        public Nullable<decimal> YZPL_SUM { get; set; }
        public string SHIFT { get; set; }
        public Nullable<decimal> FEO_YJP_DAY { get; set; }
        public Nullable<decimal> FEO_YJP_SUM { get; set; }
    }
}
