//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_SINTER_RUNSTOP
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<System.DateTime> BEGIN_STOP_TIME { get; set; }
        public Nullable<System.DateTime> END_STOP_TIME { get; set; }
        public string TEAM { get; set; }
        public string SHIFT { get; set; }
        public Nullable<decimal> STOP_TIME { get; set; }
        public string STOP_REASON { get; set; }
        public string MODIFY_PERSON { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string JUDGE_REASON { get; set; }
        public string JUDGE_PERSON { get; set; }
        public Nullable<System.DateTime> JUDGE_DATE { get; set; }
    }
}
