//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_MIX_DEVICE
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> P2AI_401131F { get; set; }
        public Nullable<decimal> P2AI_400341F { get; set; }
        public Nullable<decimal> P2AI_400371F { get; set; }
        public Nullable<decimal> P2AI_400301F { get; set; }
        public Nullable<decimal> P2AI_400331F { get; set; }
        public Nullable<decimal> P2AI_400321F { get; set; }
        public Nullable<decimal> P2AI_401221F { get; set; }
        public Nullable<decimal> P2AI_401541F { get; set; }
        public Nullable<decimal> P2AI_400591F { get; set; }
        public Nullable<decimal> P2AI_400621F { get; set; }
        public Nullable<decimal> P2AI_401111F { get; set; }
        public Nullable<decimal> P2AI_400611F { get; set; }
        public Nullable<decimal> P2AI_401121F { get; set; }
    }
}
