//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_TUOLIU_AZ
    {
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> AZ_ASBCKGDYL { get; set; }
        public Nullable<decimal> AZ_ASBCKGDLL { get; set; }
        public Nullable<decimal> AZ_ASZFQCKYL { get; set; }
        public Nullable<decimal> AZ_ASZFQCKWD { get; set; }
        public Nullable<decimal> AZ_ASZFQYW { get; set; }
        public Nullable<decimal> AZ_XSFCKLL { get; set; }
        public Nullable<decimal> AZ_AKHHQCKYL { get; set; }
        public Nullable<decimal> AZ_AKHHQCKWD { get; set; }
        public Nullable<decimal> AZ_ZQWD { get; set; }
        public Nullable<decimal> AZ_ZQYL { get; set; }
        public Nullable<decimal> AZ_ZQLL { get; set; }
        public Nullable<decimal> CW_YQ_QQYL1 { get; set; }
        public Nullable<decimal> CW_YQ_QQYL2 { get; set; }
        public Nullable<decimal> CW_YQ_HRJKYL1 { get; set; }
        public Nullable<decimal> CW_YQ_HRJKYL2 { get; set; }
        public Nullable<decimal> CW_YQ_HRCKYL { get; set; }
        public Nullable<decimal> CW_YQ_ZYFJCKYL { get; set; }
        public Nullable<decimal> CW_YQ_QQTJF_KD1 { get; set; }
        public Nullable<decimal> CW_YQ_QQTJF_KD2 { get; set; }
        public Nullable<decimal> CW_YQ_LFF_KD1 { get; set; }
        public Nullable<decimal> CW_YQ_XFTCKYQYL { get; set; }
        public Nullable<decimal> CW_YQ_XTYC { get; set; }
    }
}
