//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QUALITY_MIX_PHY_INSET
    {
        public string WP_NO { get; set; }
        public string SHIFT { get; set; }
        public string FEED_NAME { get; set; }
        public Nullable<decimal> FEED_TEM { get; set; }
        public Nullable<decimal> WATER { get; set; }
        public Nullable<decimal> GRAIN_COMP_3 { get; set; }
        public Nullable<decimal> GRAIN_COMP_31 { get; set; }
        public Nullable<decimal> GRAIN_COMP_1 { get; set; }
        public Nullable<decimal> GRAIN_COMP_63 { get; set; }
        public Nullable<decimal> GRAIN_3 { get; set; }
        public string RECORD_PERSON { get; set; }
        public System.DateTime RECORD_DATE { get; set; }
        public Nullable<decimal> GRAIN_5 { get; set; }
        public Nullable<decimal> GRAIN_05 { get; set; }
    }
}
