//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SINTER_MATERIAL_RATIO
    {
        public string PBD_NO { get; set; }
        public string MATERIAL_NAME { get; set; }
        public string MATERIAL_CODE { get; set; }
        public Nullable<decimal> MATERIAL_PERCENTAGE { get; set; }
        public Nullable<System.DateTime> BEGIN_STORE_DATE { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public string RECORD_PERSON { get; set; }
    }
}
