//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_USER
    {
        public decimal USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public Nullable<decimal> ROLE_ID { get; set; }
        public string USER_PASSWORD { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_PERSON { get; set; }
        public string USER_DEC { get; set; }
        public Nullable<System.DateTime> USER_LOGIN_DATE { get; set; }
        public Nullable<System.DateTime> USER_QUIT_DATE { get; set; }
    }
}
