//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_FUNCTION1
    {
        public string FUNCTION_CODE { get; set; }
        public string FUNCTION_DEC { get; set; }
        public string FUNCTION_NAME { get; set; }
        public string ROLE_NAME { get; set; }
        public Nullable<decimal> FUNCTION_ADD { get; set; }
        public Nullable<decimal> FUNCTION_DEL { get; set; }
        public Nullable<decimal> FUNCTION_UPDATE { get; set; }
        public Nullable<decimal> FUNCTION_QUERY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_PERSON { get; set; }
        public string FUNCTION_CLASS_DEC { get; set; }
        public Nullable<decimal> FUNCTION_SEQ { get; set; }
        public Nullable<decimal> FUNCTION_SEND { get; set; }
        public Nullable<decimal> FUNCTION_RECEIVE { get; set; }
        public string FUNCTION_FORM { get; set; }
    }
}
