//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_EMPLOYEE
    {
        public string EMPLOYEE_NAME { get; set; }
        public string EMPLOYEE_DEC { get; set; }
        public string EMPLOYEE_TEAM { get; set; }
        public string EMPLOYEE_SHIFTS { get; set; }
        public string EMPLOYEE_WORKSTATION { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_PERSON { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public Nullable<decimal> EMPLOYEE_ID { get; set; }
    }
}
