//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T_USER : DbContext
    {
        public T_USER()
            : base("name=T_USER")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_SYS_EMPLOYEE> T_SYS_EMPLOYEE { get; set; }
        public virtual DbSet<T_SYS_FUNCTION> T_SYS_FUNCTION { get; set; }
        public virtual DbSet<T_SYS_ROLE> T_SYS_ROLE { get; set; }
        public virtual DbSet<T_SYS_USER> T_SYS_USER { get; set; }
        public virtual DbSet<T_SYS_USER1> T_SYS_USER1 { get; set; }
        public virtual DbSet<T_BASE_CODE> T_BASE_CODE { get; set; }
        public virtual DbSet<T_SYS_ROLE1> T_SYS_ROLE1 { get; set; }
        public virtual DbSet<T_SYS_FUNCTION1> T_SYS_FUNCTION1 { get; set; }
    }
}
