//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jyxcsjl2.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user : DbContext
    {
        public user()
            : base("name=user")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_USER_EMPLOYEE> T_USER_EMPLOYEE { get; set; }
        public virtual DbSet<T_USER_FUNCTION> T_USER_FUNCTION { get; set; }
        public virtual DbSet<T_USER_ROLE> T_USER_ROLE { get; set; }
        public virtual DbSet<T_USER_USER> T_USER_USER { get; set; }
    }
}
